export type ProductDetailsType = {
  [key: string]: {
    id: string;
    title: string;
    price: number;
    slotsOut: number;
    slotsAvailable: number;
    description: string;
    highlights: string[];
    images: string[];
    category: string;
    countdown: number;
  };
};

const getMilliseconds = (days: number, hours: number, minutes: number, seconds: number) => {
  return ((days * 24 + hours) * 60 + minutes) * 60 * 1000 + seconds * 1000;
};

export const productDetails: ProductDetailsType = {
  "12573FG": {
    id: "12573FG",
    title: "Live Goat",
    price: 35000,
    slotsOut: 2,
    slotsAvailable: 4,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/brown-goat.png",
      "/stocksImages/black-goat.png",
      "/stocksImages/live-fish.png",
      "/stocksImages/live-ram.png",
    ],
    category: "Goat",
    countdown: getMilliseconds(23, 16, 0, 0),
  },
  "14353HY": {
    id: "14353HY",
    title: "White Cow",
    price: 78000,
    slotsOut: 5,
    slotsAvailable: 15,
    description: "A 450-kilogram brown male cow in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A male cow weighing 450 Kilograms (Kg) and white in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/white-cow.png",
      "/stocksImages/brown-cow.png",
      "/stocksImages/live-chicken.png",
      "/stocksImages/live-turkey.png",
    ],
    category: "Cow",
    countdown: getMilliseconds(25, 16, 59, 12),
  },
  "12367UT": {
    id: "12367UT",
    title: "Brown Cow",
    price: 80000,
    slotsOut: 8,
    slotsAvailable: 12,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/brown-cow.png",
      "/stocksImages/white-cow.png",
      "/stocksImages/live-chicken.png",
      "/stocksImages/live-turkey.png",
    ],
    category: "Cow",
    countdown: getMilliseconds(43, 0, 0, 0),
  },
  "43929HU": {
    id: "43929HU",
    title: "Live Chicken",
    price: 25000,
    slotsOut: 5,
    slotsAvailable: 15,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/live-chicken.png",
      "/stocksImages/live-turkey.png",
      "/stocksImages/white-cow.png",
      "/stocksImages/brown-cow.png",
    ],
    category: "Chicken",
    countdown: getMilliseconds(1, 0, 0, 0),
  },
  "12537PY": {
    id: "12537PY",
    title: "Live Turkey",
    price: 30000,
    slotsOut: 8,
    slotsAvailable: 12,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/live-turkey.png",
      "/stocksImages/live-chicken.png",
      "/stocksImages/white-cow.png",
      "/stocksImages/brown-cow.png",
    ],
    category: "Turkey",
    countdown: getMilliseconds(0, 16, 0, 0),
  },
  "16272FT": {
    id: "16272FT",
    title: "Black Goat",
    price: 55000,
    slotsOut: 5,
    slotsAvailable: 15,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/black-goat.png",
      "/stocksImages/brown-goat.png",
      "/stocksImages/live-fish.png",
      "/stocksImages/live-ram.png",
    ],
    category: "Goat",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
  "13221FT": {
    id: "13221FT",
    title: "Turkey Wings",
    price: 50000,
    slotsOut: 8,
    slotsAvailable: 12,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/turkey-wings.png",
      "/stocksImages/live-turkey.png",
      "/stocksImages/live-chicken.png",
      "/stocksImages/white-cow.png",
    ],
    category: "Turkey",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
  "11235FH": {
    id: "11235FH",
    title: "Live Ram",
    price: 75000,
    slotsOut: 5,
    slotsAvailable: 15,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/live-ram.png",
      "/stocksImages/live-fish.png",
      "/stocksImages/black-goat.png",
      "/stocksImages/brown-goat.png",
    ],
    category: "Ram",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
  "17321HS": {
    id: "17321HS",
    title: "Live Ram 2",
    price: 70000,
    slotsOut: 8,
    slotsAvailable: 12,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/live-ramm.png",
      "/stocksImages/live-ram.png",
      "/stocksImages/live-fish.png",
      "/stocksImages/black-goat.png",
    ],
    category: "Ram",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
  "16352SD": {
    id: "16352SD",
    title: "Live Cow",
    price: 75000,
    slotsOut: 5,
    slotsAvailable: 15,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/live-cow.png",
      "/stocksImages/live-ram.png",
      "/stocksImages/live-fish.png",
      "/stocksImages/black-goat.png",
    ],
    category: "Cow",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
  "11263HD": {
    id: "11263HD",
    title: "Whole Chicken",
    price: 100000,
    slotsOut: 8,
    slotsAvailable: 12,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/whole-chicken.png",
      "/stocksImages/live-chicken.png",
      "/stocksImages/live-turkey.png",
      "/stocksImages/white-cow.png",
    ],
    category: "Chicken",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
  "12462HW": {
    id: "12462HW",
    title: "Live Fish",
    price: 75000,
    slotsOut: 5,
    slotsAvailable: 15,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/live-fish.png",
      "/stocksImages/live-ram.png",
      "/stocksImages/black-goat.png",
      "/stocksImages/brown-goat.png",
    ],
    category: "Fish",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
  "173G5G": {
    id: "173G5G",
    title: "Live Pig",
    price: 60000,
    slotsOut: 8,
    slotsAvailable: 12,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/live-pig.png",
      "/stocksImages/live-ramm.png",
      "/stocksImages/live-fish.png",
      "/stocksImages/live-catfish.png",
    ],
    category: "Pig",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
  "16252SD": {
    id: "16252SD",
    title: "Live Catfish",
    price: 20000,
    slotsOut: 5,
    slotsAvailable: 15,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/live-catfish.png",
      "/stocksImages/live-pig.png",
      "/stocksImages/large-white-pig.png",
      "/stocksImages/black-white-pig.png",
    ],
    category: "Fish",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
  "19263HU": {
    id: "19263HU",
    title: "Large White Pig",
    price: 95000,
    slotsOut: 8,
    slotsAvailable: 12,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/large-white-pig.png",
      "/stocksImages/live-pig.png",
      "/stocksImages/black-white-pig.png",
      "/stocksImages/live-catfish.png",
    ],
    category: "Pig",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
  "12962PW": {
    id: "12962PW",
    title: "Black & White Pig",
    price: 58500,
    slotsOut: 5,
    slotsAvailable: 15,
    description: "A 200-kilogram brown female goat in Lagos has been certified healthy by the Lagos State Ministry of Agriculture.",
    highlights: [
      "A female goat weighing 200 Kilograms (Kg) and brown in color.",
      "The goat has been certified with a Veterinary Health Certificate (VHC) by the Lagos State Ministry of Agriculture.",
      "The full price of the goat is ₦140,000, however, the meat-sharing price is ₦35,000.",
      "The slaughter date and processing date is on the 16th of May, 2024.",
      "The delivery is within Lagos State and will be completed on the same day as the meat-sharing event.",
    ],
    images: [
      "/stocksImages/black-white-pig.png",
      "/stocksImages/live-pig.png",
      "/stocksImages/large-white-pig.png",
      "/stocksImages/live-catfish.png",
    ],
    category: "Pig",
    countdown: getMilliseconds(23, 16, 59, 12),
  },
};