export const productListData = [
  {
    productId: "INV001",
    productName: "Product A",
    grossPrice: "$250.00",
    netPrice: "$250.00",
    totalSlot: 4,
    availableSlot: 2,
    status: "Completed",
  },

  {
    productId: "INV002",
    productName: "Product B",
    grossPrice: "$150.00",
    netPrice: "$150.00",
    totalSlot: 5,
    availableSlot: 3,
    status: "Pending",
  },
  {
    productId: "INV003",
    productName: "Product C",
    grossPrice: "$300.00",
    netPrice: "$300.00",
    totalSlot: 6,
    availableSlot: 1,
    status: "Completed",
  },
  {
    productId: "INV004",
    productName: "Product D",
    grossPrice: "$200.00",
    netPrice: "$200.00",
    totalSlot: 3,
    availableSlot: 0,
    status: "Cancel",
  },
  {
    productId: "INV005",
    productName: "Product E",
    grossPrice: "$100.00",
    netPrice: "$100.00",
    totalSlot: 8,
    availableSlot: 5,
    status: "Pending",
  },
  {
    productId: "INV006",
    productName: "Product F",
    grossPrice: "$400.00",
    netPrice: "$400.00",
    totalSlot: 2,
    availableSlot: 2,
    status: "Completed",
  },
  {
    productId: "INV007",
    productName: "Product G",
    grossPrice: "$350.00",
    netPrice: "$350.00",
    totalSlot: 7,
    availableSlot: 4,
    status: "Pending",
  },
  {
    productId: "INV008",
    productName: "Product H",
    grossPrice: "$500.00",
    netPrice: "$500.00",
    totalSlot: 1,
    availableSlot: 0,
    status: "Cancel",
  },
  {
    productId: "INV009",
    productName: "Product I",
    grossPrice: "$275.00",
    netPrice: "$275.00",
    totalSlot: 4,
    availableSlot: 1,
    status: "Completed",
  },
  {
    productId: "INV010",
    productName: "Product J",
    grossPrice: "$125.00",
    netPrice: "$125.00",
    totalSlot: 5,
    availableSlot: 3,
    status: "Pending",
  },
  {
    productId: "INV011",
    productName: "Product K",
    grossPrice: "$225.00",
    netPrice: "$225.00",
    totalSlot: 6,
    availableSlot: 2,
    status: "Completed",
  },
  {
    productId: "INV012",
    productName: "Product L",
    grossPrice: "$175.00",
    netPrice: "$175.00",
    totalSlot: 3,
    availableSlot: 1,
    status: "Cancel",
  },
  {
    productId: "INV013",
    productName: "Product M",
    grossPrice: "$275.00",
    netPrice: "$275.00",
    totalSlot: 4,
    availableSlot: 2,
    status: "Pending",
  },
  {
    productId: "INV014",
    productName: "Product N",
    grossPrice: "$325.00",
    netPrice: "$325.00",
    totalSlot: 5,
    availableSlot: 4,
    status: "Completed",
  },
  {
    productId: "INV015",
    productName: "Product O",
    grossPrice: "$375.00",
    netPrice: "$375.00",
    totalSlot: 2,
    availableSlot: 0,
    status: "Cancel",
  },
  {
    productId: "INV016",
    productName: "Product P",
    grossPrice: "$425.00",
    netPrice: "$425.00",
    totalSlot: 6,
    availableSlot: 3,
    status: "Pending",
  },
];
