export const paymentRequestData = [
  {
    date: "24/05/2024",
    amount: "$250.00",
    accountNumber: "xxxxxxx789",
    bankName: "UBA",
    name: "Ade Love",
    status: "Approved",
  },
  {
    date: "25/05/2024",
    amount: "$300.00",
    accountNumber: "xxxxxxx123",
    bankName: "GTBank",
    name: "John Doe",
    status: "Declined",
  },
  {
    date: "26/05/2024",
    amount: "$150.00",
    accountNumber: "xxxxxxx456",
    bankName: "Zenith Bank",
    name: "Jane Smith",
    status: "Approved",
  },
  {
    date: "27/05/2024",
    amount: "$500.00",
    accountNumber: "xxxxxxx789",
    bankName: "Access Bank",
    name: "Michael Johnson",
    status: "------------",
  },
  {
    date: "28/05/2024",
    amount: "$200.00",
    accountNumber: "xxxxxxx321",
    bankName: "First Bank",
    name: "Emily Davis",
    status: "Approved",
  },
  {
    date: "29/05/2024",
    amount: "$350.00",
    accountNumber: "xxxxxxx654",
    bankName: "Stanbic IBTC",
    name: "Chris Brown",
    status: "Declined",
  },
  {
    date: "30/05/2024",
    amount: "$400.00",
    accountNumber: "xxxxxxx987",
    bankName: "Union Bank",
    name: "Patricia Miller",
    status: "Approved",
  },
  {
    date: "31/05/2024",
    amount: "$450.00",
    accountNumber: "xxxxxxx741",
    bankName: "Fidelity Bank",
    name: "Robert Wilson",
    status: "------------",
  },
  {
    date: "01/06/2024",
    amount: "$600.00",
    accountNumber: "xxxxxxx852",
    bankName: "EcoBank",
    name: "Linda Taylor",
    status: "Approved",
  },
  {
    date: "02/06/2024",
    amount: "$700.00",
    accountNumber: "xxxxxxx963",
    bankName: "Wema Bank",
    name: "James Anderson",
    status: "Declined",
  },
  {
    date: "03/06/2024",
    amount: "$800.00",
    accountNumber: "xxxxxxx159",
    bankName: "Sterling Bank",
    name: "Barbara Thomas",
    status: "Approved",
  },
  {
    date: "04/06/2024",
    amount: "$900.00",
    accountNumber: "xxxxxxx753",
    bankName: "Keystone Bank",
    name: "Paul Martinez",
    status: "------------",
  },
  {
    date: "05/06/2024",
    amount: "$1000.00",
    accountNumber: "xxxxxxx951",
    bankName: "Unity Bank",
    name: "Nancy Hernandez",
    status: "Approved",
  },
  {
    date: "06/06/2024",
    amount: "$1100.00",
    accountNumber: "xxxxxxx357",
    bankName: "Heritage Bank",
    name: "Kevin Clark",
    status: "Declined",
  },
  {
    date: "07/06/2024",
    amount: "$1200.00",
    accountNumber: "xxxxxxx258",
    bankName: "Polaris Bank",
    name: "Sarah Lewis",
    status: "Approved",
  },
];
