export const TotalSellersData = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    stocksSold: 150,
    registered: "08.08.2024",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    stocksSold: 300,
    registered: "08.08.2024",
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    stocksSold: 200,
    registered: "08.08.2024",
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    stocksSold: 120,
    registered: "08.08.2024",
  },
  {
    id: "5",
    firstName: "Chris",
    lastName: "Brown",
    email: "chris.brown@example.com",
    stocksSold: 95,
    registered: "08.08.2024",
  },
  {
    id: "6",
    firstName: "Laura",
    lastName: "Wilson",
    email: "laura.wilson@example.com",
    stocksSold: 175,
    registered: "08.08.2024",
  },
  {
    id: "7",
    firstName: "David",
    lastName: "Martinez",
    email: "david.martinez@example.com",
    stocksSold: 250,
    registered: "08.08.2024",
  },
  {
    id: "8",
    firstName: "Sophia",
    lastName: "Anderson",
    email: "sophia.anderson@example.com",
    stocksSold: 310,
    registered: "08.08.2024",
  },
  {
    id: "9",
    firstName: "Daniel",
    lastName: "Thomas",
    email: "daniel.thomas@example.com",
    stocksSold: 400,
    registered: "08.08.2024",
  },
  {
    id: "10",
    firstName: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@example.com",
    stocksSold: 220,
    registered: "08.08.2024",
  },
  {
    id: "11",
    firstName: "James",
    lastName: "Moore",
    email: "james.moore@example.com",
    stocksSold: 180,
    registered: "08.08.2024",
  },
  {
    id: "12",
    firstName: "Isabella",
    lastName: "Jackson",
    email: "isabella.jackson@example.com",
    stocksSold: 145,
    registered: "08.08.2024",
  },
  {
    id: "13",
    firstName: "Ethan",
    lastName: "White",
    email: "ethan.white@example.com",
    stocksSold: 270,
    registered: "08.08.2024",
  },
  {
    id: "14",
    firstName: "Mia",
    lastName: "Harris",
    email: "mia.harris@example.com",
    stocksSold: 190,
    registered: "08.08.2024",
  },
  {
    id: "15",
    firstName: "Benjamin",
    lastName: "Martin",
    email: "benjamin.martin@example.com",
    stocksSold: 320,
    registered: "08.08.2024",
  },
];
