export const TotalSellersData = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    stocksSold: 150,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    stocksSold: 300,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    stocksSold: 200,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: false,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    stocksSold: 120,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "5",
    firstName: "Chris",
    lastName: "Brown",
    email: "chris.brown@example.com",
    stocksSold: 95,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "6",
    firstName: "Laura",
    lastName: "Wilson",
    email: "laura.wilson@example.com",
    stocksSold: 175,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: false,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "7",
    firstName: "David",
    lastName: "Martinez",
    email: "david.martinez@example.com",
    stocksSold: 250,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "8",
    firstName: "Sophia",
    lastName: "Anderson",
    email: "sophia.anderson@example.com",
    stocksSold: 310,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "9",
    firstName: "Daniel",
    lastName: "Thomas",
    email: "daniel.thomas@example.com",
    stocksSold: 400,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "10",
    firstName: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@example.com",
    stocksSold: 220,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "11",
    firstName: "James",
    lastName: "Moore",
    email: "james.moore@example.com",
    stocksSold: 180,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "12",
    firstName: "Isabella",
    lastName: "Jackson",
    email: "isabella.jackson@example.com",
    stocksSold: 145,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "13",
    firstName: "Ethan",
    lastName: "White",
    email: "ethan.white@example.com",
    stocksSold: 270,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "14",
    firstName: "Mia",
    lastName: "Harris",
    email: "mia.harris@example.com",
    stocksSold: 190,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: true,
    sellerImage: "/admin_profile.png",
  },
  {
    id: "15",
    firstName: "Benjamin",
    lastName: "Martin",
    email: "benjamin.martin@example.com",
    stocksSold: 320,
    registered: "08.08.2024",
    phoneNumber: "57679843875723409",
    optionalPhoneNumber: "",
    userType: "Buyer",
    gender: "Male",
    active: false,
    sellerImage: "/admin_profile.png",
  },
{
  id: "16",
  firstName: "Ava",
  lastName: "Garcia",
  email: "ava.garcia@example.com",
  stocksSold: 210,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "17",
  firstName: "Lucas",
  lastName: "Martinez",
  email: "lucas.martinez@example.com",
  stocksSold: 330,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "18",
  firstName: "Charlotte",
  lastName: "Rodriguez",
  email: "charlotte.rodriguez@example.com",
  stocksSold: 140,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "19",
  firstName: "Henry",
  lastName: "Martinez",
  email: "henry.martinez@example.com",
  stocksSold: 290,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "20",
  firstName: "Amelia",
  lastName: "Hernandez",
  email: "amelia.hernandez@example.com",
  stocksSold: 160,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "21",
  firstName: "Jack",
  lastName: "Lopez",
  email: "jack.lopez@example.com",
  stocksSold: 240,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "22",
  firstName: "Harper",
  lastName: "Gonzalez",
  email: "harper.gonzalez@example.com",
  stocksSold: 180,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "23",
  firstName: "Sebastian",
  lastName: "Wilson",
  email: "sebastian.wilson@example.com",
  stocksSold: 260,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "24",
  firstName: "Evelyn",
  lastName: "Anderson",
  email: "evelyn.anderson@example.com",
  stocksSold: 220,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "25",
  firstName: "Alexander",
  lastName: "Thomas",
  email: "alexander.thomas@example.com",
  stocksSold: 300,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "26",
  firstName: "Abigail",
  lastName: "Taylor",
  email: "abigail.taylor@example.com",
  stocksSold: 190,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "27",
  firstName: "Matthew",
  lastName: "Moore",
  email: "matthew.moore@example.com",
  stocksSold: 280,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "28",
  firstName: "Sofia",
  lastName: "Jackson",
  email: "sofia.jackson@example.com",
  stocksSold: 210,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "29",
  firstName: "Joseph",
  lastName: "White",
  email: "joseph.white@example.com",
  stocksSold: 270,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "30",
  firstName: "Ella",
  lastName: "Harris",
  email: "ella.harris@example.com",
  stocksSold: 230,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "31",
  firstName: "Samuel",
  lastName: "Martin",
  email: "samuel.martin@example.com",
  stocksSold: 320,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "32",
  firstName: "Grace",
  lastName: "Thompson",
  email: "grace.thompson@example.com",
  stocksSold: 150,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "33",
  firstName: "David",
  lastName: "Garcia",
  email: "david.garcia@example.com",
  stocksSold: 310,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "34",
  firstName: "Chloe",
  lastName: "Martinez",
  email: "chloe.martinez@example.com",
  stocksSold: 170,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "35",
  firstName: "Daniel",
  lastName: "Rodriguez",
  email: "daniel.rodriguez@example.com",
  stocksSold: 290,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "36",
  firstName: "Lily",
  lastName: "Hernandez",
  email: "lily.hernandez@example.com",
  stocksSold: 160,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "37",
  firstName: "Andrew",
  lastName: "Lopez",
  email: "andrew.lopez@example.com",
  stocksSold: 240,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "38",
  firstName: "Zoe",
  lastName: "Gonzalez",
  email: "zoe.gonzalez@example.com",
  stocksSold: 180,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "39",
  firstName: "Joshua",
  lastName: "Wilson",
  email: "joshua.wilson@example.com",
  stocksSold: 260,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "40",
  firstName: "Hannah",
  lastName: "Anderson",
  email: "hannah.anderson@example.com",
  stocksSold: 220,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "41",
  firstName: "Christopher",
  lastName: "Thomas",
  email: "christopher.thomas@example.com",
  stocksSold: 300,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "42",
  firstName: "Victoria",
  lastName: "Taylor",
  email: "victoria.taylor@example.com",
  stocksSold: 190,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "43",
  firstName: "Ryan",
  lastName: "Moore",
  email: "ryan.moore@example.com",
  stocksSold: 280,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "44",
  firstName: "Aria",
  lastName: "Jackson",
  email: "aria.jackson@example.com",
  stocksSold: 210,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "45",
  firstName: "Nathan",
  lastName: "White",
  email: "nathan.white@example.com",
  stocksSold: 270,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "46",
  firstName: "Scarlett",
  lastName: "Harris",
  email: "scarlett.harris@example.com",
  stocksSold: 230,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "47",
  firstName: "Isaac",
  lastName: "Martin",
  email: "isaac.martin@example.com",
  stocksSold: 320,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "48",
  firstName: "Penelope",
  lastName: "Thompson",
  email: "penelope.thompson@example.com",
  stocksSold: 150,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "49",
  firstName: "Gabriel",
  lastName: "Garcia",
  email: "gabriel.garcia@example.com",
  stocksSold: 310,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Male",
  active: true,
  sellerImage: "/admin_profile.png",
},
{
  id: "50",
  firstName: "Layla",
  lastName: "Martinez",
  email: "layla.martinez@example.com",
  stocksSold: 170,
  registered: "08.08.2024",
  phoneNumber: "57679843875723409",
  optionalPhoneNumber: "",
  userType: "Buyer",
  gender: "Female",
  active: true,
  sellerImage: "/admin_profile.png",
}
];
