const stocks = [
  {
    id: "12573FG",
    title: "Brown Goat",
    image: "/stocksImages/brown-goat.png",
    price: 35000,
    slotsOut: 10,
    slotsAvailable: 20,
    category: "Goat",
  },
  {
    id: "14353HY",
    title: "White Cow",
    image: "/stocksImages/white-cow.png",
    price: 78000,
    slotsOut: 5,
    slotsAvailable: 15,
    category: "Cow",
  },
  {
    id: "12367UT",
    title: "Brown Cow",
    image: "/stocksImages/brown-cow.png",
    price: 80000,
    slotsOut: 8,
    slotsAvailable: 12,
    category: "Cow",
  },
  {
    id: "43929HU",
    title: "Live Chicken",
    image: "/stocksImages/live-chicken.png",
    price: 25000,
    slotsOut: 5,
    slotsAvailable: 15,
    category: "Chicken",
  },
  {
    id: "12537PY",
    title: "Live Turkey",
    image: "/stocksImages/live-turkey.png",
    price: 30000,
    slotsOut: 8,
    slotsAvailable: 12,
    category: "Turkey",
  },
  {
    id: "16272FT",
    title: "Black Goat",
    image: "/stocksImages/black-goat.png",
    price: 55000,
    slotsOut: 5,
    slotsAvailable: 15,
    category: "Goat",
  },
  {
    id: "13221FT",
    title: "Turkey Wings",
    image: "/stocksImages/turkey-wings.png",
    price: 50000,
    slotsOut: 8,
    slotsAvailable: 12,
    category: "Turkey",
  },
  {
    id: "11235FH",
    title: "Live Ram",
    image: "/stocksImages/live-ram.png",
    price: 75000,
    slotsOut: 5,
    slotsAvailable: 15,
    category: "Ram",
  },
  {
    id: "17321HS",
    title: "Live Ram 2",
    image: "/stocksImages/live-ramm.png",
    price: 70000,
    slotsOut: 8,
    slotsAvailable: 12,
    category: "Ram",
  },
  {
    id: "16352SD",
    title: "Live Cow",
    image: "/stocksImages/live-cow.png",
    price: 75000,
    slotsOut: 5,
    slotsAvailable: 15,
    category: "Cow",
  },
  {
    id: "11263HD",
    title: "Whole Chicken",
    image: "/stocksImages/whole-chicken.png",
    price: 100000,
    slotsOut: 8,
    slotsAvailable: 12,
    category: "Chicken",
  },
  {
    id: "12462HW",
    title: "Live Fish",
    image: "/stocksImages/live-fish.png",
    price: 75000,
    slotsOut: 5,
    slotsAvailable: 15,
    category: "Fish",
  },
  {
    id: "173G5G",
    title: "Live Pig",
    image: "/stocksImages/live-pig.jpg",
    price: 60000,
    slotsOut: 8,
    slotsAvailable: 12,
    category: "Pig",
  },
  {
    id: "16252SD",
    title: "Live Catfish",
    image: "/stocksImages/live-catfish.png",
    price: 20000,
    slotsOut: 5,
    slotsAvailable: 15,
    category: "Fish",
  },
  {
    id: "19263HU",
    title: "Large White Pig",
    image: "/stocksImages/large-white-pig.jpg",
    price: 95000,
    slotsOut: 8,
    slotsAvailable: 12,
    category: "Pig",
  },
  {
    id: "12962PW",
    title: "Black & White Pig",
    image: "/stocksImages/black-white-pig.jpg",
    price: 58500,
    slotsOut: 5,
    slotsAvailable: 15,
    category: "Pig",
  },
];

export default stocks;
