const FallBackStocks = [
    {
        productId: "12573FG",
        productName: "Brown Goat",
       healthSatisfactionImage: "/stocksImages/brown-goat.png",
        productPrice: 35000,
        slotsOut: 10,
        totalSlots: 20,
        category: "Goat",
    },
    {
        productId: "14353HY",
        productName: "White Cow",
       healthSatisfactionImage: "/stocksImages/white-cow.png",
        productPrice: 78000,
        slotsOut: 5,
        totalSlots: 15,
        category: "Cow",
    },
    {
        productId: "12367UT",
        productName: "Brown Cow",
       healthSatisfactionImage: "/stocksImages/brown-cow.png",
        productPrice: 80000,
        slotsOut: 8,
        totalSlots: 12,
        category: "Cow",
    },
    {
        productId: "43929HU",
        productName: "Live Chicken",
       healthSatisfactionImage: "/stocksImages/live-chicken.png",
        productPrice: 25000,
        slotsOut: 5,
        totalSlots: 15,
        category: "Chicken",
    },
    {
        productId: "12537PY",
        productName: "Live Turkey",
       healthSatisfactionImage: "/stocksImages/live-turkey.png",
        productPrice: 30000,
        slotsOut: 8,
        totalSlots: 12,
        category: "Turkey",
    },
    {
        productId: "16272FT",
        productName: "Black Goat",
       healthSatisfactionImage: "/stocksImages/black-goat.png",
        productPrice: 55000,
        slotsOut: 5,
        totalSlots: 15,
        category: "Goat",
    },
    {
        productId: "13221FT",
        productName: "Turkey Wings",
       healthSatisfactionImage: "/stocksImages/turkey-wings.png",
        productPrice: 50000,
        slotsOut: 8,
        totalSlots: 12,
        category: "Turkey",
    },
    {
        productId: "11235FH",
        productName: "Live Ram",
       healthSatisfactionImage: "/stocksImages/live-ram.png",
        productPrice: 75000,
        slotsOut: 5,
        totalSlots: 15,
        category: "Ram",
    },
    {
        productId: "17321HS",
        productName: "Live Ram 2",
       healthSatisfactionImage: "/stocksImages/live-ramm.png",
        productPrice: 70000,
        slotsOut: 8,
        totalSlots: 12,
        category: "Ram",
    },
    {
        productId: "16352SD",
        productName: "Live Cow",
       healthSatisfactionImage: "/stocksImages/live-cow.png",
        productPrice: 75000,
        slotsOut: 5,
        totalSlots: 15,
        category: "Cow",
    },
    {
        productId: "11263HD",
        productName: "Whole Chicken",
       healthSatisfactionImage: "/stocksImages/whole-chicken.png",
        productPrice: 100000,
        slotsOut: 8,
        totalSlots: 12,
        category: "Chicken",
    },
    {
        productId: "12462HW",
        productName: "Live Fish",
       healthSatisfactionImage: "/stocksImages/live-fish.png",
        productPrice: 75000,
        slotsOut: 5,
        totalSlots: 15,
        category: "Fish",
    },
    {
        productId: "173G5G",
        productName: "Live Pig",
       healthSatisfactionImage: "/stocksImages/live-pig.png",
        productPrice: 60000,
        slotsOut: 8,
        totalSlots: 12,
        category: "Pig",
    },
    {
        productId: "16252SD",
        productName: "Live Catfish",
       healthSatisfactionImage: "/stocksImages/live-catfish.png",
        productPrice: 20000,
        slotsOut: 5,
        totalSlots: 15,
        category: "Fish",
    },
    {
        productId: "19263HU",
        productName: "Large White Pig",
       healthSatisfactionImage: "/stocksImages/large-white-pig.png",
        productPrice: 95000,
        slotsOut: 8,
        totalSlots: 12,
        category: "Pig",
    },
    {
        productId: "12962PW",
        productName: "Black & White Pig",
       healthSatisfactionImage: "/stocksImages/black-white-pig.png",
        productPrice: 58500,
        slotsOut: 5,
        totalSlots: 15,
        category: "Pig",
    },
];

export default FallBackStocks;
