export const TotalBuyersData = [
    {
      id: "1",
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      orders: 50,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: false
    },
    {
      id: "2",
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
      orders: 3,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "3",
      firstName: "Michael",
      lastName: "Johnson",
      email: "michael.johnson@example.com",
      orders: 20,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "4",
      firstName: "Emily",
      lastName: "Davis",
      email: "emily.davis@example.com",
      orders: 12,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "5",
      firstName: "Chris",
      lastName: "Brown",
      email: "chris.brown@example.com",
      orders: 9,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: false
    },
    {
      id: "6",
      firstName: "Laura",
      lastName: "Wilson",
      email: "laura.wilson@example.com",
      orders: 75,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "7",
      firstName: "David",
      lastName: "Martinez",
      email: "david.martinez@example.com",
      orders: 25,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "8",
      firstName: "Sophia",
      lastName: "Anderson",
      email: "sophia.anderson@example.com",
      orders: 10,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "9",
      firstName: "Daniel",
      lastName: "Thomas",
      email: "daniel.thomas@example.com",
      orders: 40,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: false
    },
    {
      id: "10",
      firstName: "Olivia",
      lastName: "Taylor",
      email: "olivia.taylor@example.com",
      orders: 22,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "11",
      firstName: "James",
      lastName: "Moore",
      email: "james.moore@example.com",
      orders: 18,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "12",
      firstName: "Isabella",
      lastName: "Jackson",
      email: "isabella.jackson@example.com",
      orders: 45,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "13",
      firstName: "Ethan",
      lastName: "White",
      email: "ethan.white@example.com",
      orders: 38,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "14",
      firstName: "Mia",
      lastName: "Harris",
      email: "mia.harris@example.com",
      orders: 19,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
    {
      id: "15",
      firstName: "Benjamin",
      lastName: "Martin",
      email: "benjamin.martin@example.com",
      orders: 32,
      registered: "08.08.2024",
      phoneNumber: "57679843875723409",
      optionalPhoneNumber: "",
      userType: "Buyer",
      gender: "Male",
      buyerImage: "/admin_profile.png",
      active: true
    },
  ];
  